---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    projcet: roboshop
    tier: app
data:
  CART_ENDPOINT: cart:8080
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
        - name: shipping
          image: vinodkumar9618/shipping:v1
          envFrom:
            - configMapRef: null
              name: shipping

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    projcet: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port